language: ruby
rvm:
  - ruby-head
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - 2.1.10
  - 2.0.0
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
matrix:
  exclude:
    - rvm: 2.4.2
      os: osx
    - rvm: ruby-head
      os: osx
before_install:
  - bundle install
install:
  - rake install
script:
  - rake test
notification:
  email:
    - tad.a.digger@gmail.com
