language: ruby
rvm:
  - ruby-head
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - 2.1.10
  - 2.0.0
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
osx_image: xcode9.1
matrix:
  exclude:
    - rvm: 2.0.0
      os: osx
  include:
    - rvm: 2.0.0
      os: osx
      osx_image: xcode7.3
before_install:
  - gem install test-unit
install:
  - rake install
script:
  - rake test
notification:
  email:
    - tad.a.digger@gmail.com
