environment:
  matrix:
    - RUBY_VERSION: 24
    - RUBY_VERSION: 24-x64
    - RUBY_VERSION: 23
    - RUBY_VERSION: 23-x64
    - RUBY_VERSION: 22
    - RUBY_VERSION: 22-x64
    - RUBY_VERSION: 21
    - RUBY_VERSION: 21-x64
    - RUBY_VERSION: 200
    - RUBY_VERSION: 200-x64
install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;C:\Ruby%RUBY_VERSION%\DevKit\bin;%PATH%
  - gem install test-unit
  - rake install
build: off
before_test:
  - ruby -v
  - gem -v
test_script:
  - rake test
